import { Editor } from "@/components/Editor";
import React from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";
type EditorPageProps = {
  game_id: string;
};

export default function EditorPage({ game_id }: EditorPageProps) {
  return (
    <>
      <Head>
        <title>Crossword</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Editor gameId={game_id} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps<
  EditorPageProps,
  { id: string }
> = async ({ params }) => {
  return {
    props: {
      game_id: params?.id ?? "",
    },
  };
};
