import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white w-full h-full absolute flex">
        <Link href="/game/hi">
          <div className="bg-green-500 p-2">Click here to start game</div>
        </Link>
      </div>
    </>
  );
}
